### PR TITLE
Add social share buttons (LinkedIn, Facebook, Twitter and G+)

### PR DESCRIPTION
**Pull request by ermauliks**
This pull request also takes care of #6.

### CODE REVIEW

**Comment by karthikb351** [comment]
We are currently scrambling to manage the traffic and flood of issues. I'll address all PRs in the night, once the traffic is less? Hope that's okay!

Thanks :)

**Comment by ermauliks** [comment]
@karthikb351 thats great to hear.
I thought adding social share buttons are important because it'll help us more to get more traffic :)

**Comment by karthikb351** [comment]
@ermauliks That will continue tomorrow as well hopefully:P

**Comment by ermauliks** [comment]
@karthikb351 definitely :D

**Comment by asdofindia** [comment]
We've changed the workflow a bit. Please make pull requests against the `stage` branch. [See here](https://github.com/netneutrality/savetheinternet.in#code) for instructions.

Also, do you think we should switch to something lighter like href based share or http://socialitejs.com/ ?

And, nice job on app.js :smiley:

**Pull request closed without merging**
